### ISSUE TITLE
[Bug]: Not really a bug...

### ISSUE THREAD

**Issue by PickyPixelStudio** [terrarium-earth/Prometheus#14]
### Bug Description

Hey 

We just want to know, how to get access to the UI of Prometheus.
Seems impossible to find a way.

### Version

1.2.1

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
There isnt just 1 UI in Prometheus, if you mean roles and permissions you can do /roles for giving a member a role you do /member all other commands are documented on https://docs.terrarium.earth/docs/prometheus/intro

**Comment by PickyPixelStudio** [comment]
I found the roles command, but not the member one. Not really clear to be honest =/
thanks for the help!
