### ISSUE TITLE
[Bug]: Basic Directions for use

### ISSUE THREAD

**Issue by myers** [terrarium-earth/Prometheus#22]
### Bug Description

https://modrinth.com/mod/prometheus should have basic directions for use.  You show a nice GUI for editing permissions, but how does one open that?

### Version

1.4.2

### Mod Loader Version

fabric

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
https://docs.terrarium.earth/docs/prometheus/intro

**Comment by myers** [comment]
@ThatGravyBoat thank you so much.  May I suggest that you update the description at https://modrinth.com/mod/prometheus and the README.md for this repo with that link?  Also that link would be much nicer if it starts with a brief description of what this mod does.

Only after I installed it did I think I figure out that you need it installed on both client and server.

**Comment by CodexAdrian** [comment]
It is not possible in Minecraft Java to show a custom GUI to a user without a client mod. The mod *does* work completely server side, but you need the mod on the client in order to see any custom UIs

**Comment by myers** [comment]
@CodexAdrian thank you.  I think this is a great idea, and makes things easier and built in to minecraft.  I like it.  My request here is just better documentation so that new users know what is happening :)
