### ISSUE TITLE
[Bug]: Mod doesn't recognize custom permissions.

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [terrarium-earth/Prometheus#31]
### Bug Description

When setting up styles in `styledchat`, it allows me to set a permission name. When I attempt to add the permission to a role in prometheus, it just straight up ignores it.

### How to Reproduce?

Create any custom permission
add it to a role
tada it dont work

### Expected Behavior

that it accepts the permission

### Version

1.3.1

### Mod Loader Version

1.20.2-0.15.11

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Kazuhiko-Gushiken** [comment]
Just tested with a newer version, 1.20.1-1.2.5, the one released in march of this year. the custom permissions still don't seem to work. if you'd like me to test something to make sure i'm actually setting it up right, do let me know, but it should be set up properly.

**Comment by ThatGravyBoat** [comment]
This was fixed in 1.20.5+ this can be backported but the current effort is to move forward
