### ISSUE TITLE
[Feature Request]: LuckPerms support

### ISSUE THREAD

**Issue by Sam-Chai** [terrarium-earth/Prometheus#32]
### Is your feature request related to a problem?

LuckPerms have more modern and eazy permission features. I think Prometheus /roles need support LuckPerms.

### Solution(s)

Such as input permission code on /roles gui, and also sync LuckPerms' group and user permissions.

### Describe alternatives you've considered

well, for now, I need to manage two permissions, the first is Prometheus', and LuckPerms. These two permission manage system did not take any sync features.

### Mod Version

1.2.5

### Mod Loader Version

1.20.1-0.15.11

### Mod Loader

Fabric

### Additional context

If I have time, I think I can PR this features.

**Comment by ThatGravyBoat** [comment]
This has been supported in newer versions as of right now this is not backported unless someone opens a PR
