### ISSUE TITLE
[Feature Request]: Improve the home teleport

### ISSUE THREAD

**Issue by Cinex20** [terrarium-earth/Prometheus#8]
### Is your feature request related to a problem?

The home command currently teleports the user to the 0 0 0 coordinates of the block where the home was set. This creates 2 issues:
1. The player is teleported to the corner of 4 different blocks, potentially partially inside a wall or in a spot where there is no ground to stand on.
2. If the home was set on a slab or any other non-full block, the teleporting player might phase through the ground.

### Solution(s)

Make the command teleport the player to the middle of the block (0.5 ~ 0.5) and remember the Y coordinates.

### Mod Version

forge-1.20.1-1.1.0

### Mod Loader Version

47.1.44

### Mod Loader

Forge

**Comment by bconlon1** [comment]
Can be closed by ffb797719d30586115c943cea158980ff9f9f918
