### ISSUE TITLE
[Bug]: SaveHandler not found.

### ISSUE THREAD

**Issue by bconlon1** [terrarium-earth/Prometheus#9]
### Bug Description

When a player attempts to chat, the server throws a missing class error for SaveHandler from MuteHandler.

### How to Reproduce?

1. Have Prometheus and ResourcefulLib installed on a server.
2. Chat.
3. See the error in the server log.

### Expected Behavior

The server would not throw an error, and would be able to find the missing class in question.

### Version

1.1.0

### Mod Loader Version

1.20.1 - 47.1.0

### Logs or additional context

https://gist.github.com/bconlon1/2da72d5ddf40240a88da3ba092297184

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Please provide your whole log, also make sure you are on the latest version of resourceful lib

**Comment by bconlon1** [comment]
Using the latest versions of Prometheus (1.2.0) and Resourceful Lib (2.1.11): https://gist.github.com/bconlon1/a3c1c502cfc120c1ae254ba7efc3adb2
